//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RequestBodies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestBodies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.RequestBodies", typeof(RequestBodies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Stops&quot;: [
        ///    {
        ///      &quot;Latitude&quot;: 46.94753769790697,
        ///      &quot;Longitude&quot;: 7.4395036697387695
        ///    },
        ///    {
        ///      &quot;Latitude&quot;: 46.90992922143335,
        ///      &quot;Longitude&quot;: 7.471003532409668
        ///    },
        ///    {
        ///      &quot;Latitude&quot;: 46.92040187442259,
        ///      &quot;Longitude&quot;: 7.413443326950073
        ///    },
        ///
        ///    {
        ///      &quot;Latitude&quot;: 46.92716147481122,
        ///      &quot;Longitude&quot;: 7.3767077922821045
        ///    },
        ///    {
        ///      &quot;Latitude&quot;: 46.95574020712597,
        ///      &quot;Longitude&quot;: 	7.481389045715332
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string TestRoute1 {
            get {
                return ResourceManager.GetString("TestRoute1", resourceCulture);
            }
        }
    }
}
